version: 2.1

orbs:
  node: circleci/node@4.1
  docker: circleci/docker@1.7.0

jobs:
  run-docker-container:
    docker:
      - image: cimg/node:12.19.0
    executor: docker/docker
    working_directory: ~/app

    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Application Docker Image
          command: |
            docker build -t khoitrinhnguyen1998/take-home-a2:latest .

workflows:
  sample:
    jobs:
      - run-docker-container
